version: '3'

services:

  game-nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "3100:80"
    networks:
      - backend
      - default
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf/logs:/var/log/nginx:rw
      - ./nginx-conf/vhost.d:/etc/nginx/vhost.d
      - ./nginx-conf/conf.d/game-dev/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:rw
      - ./nginx-conf/certs:/etc/nginx/certs:rw
    depends_on:
      - game-server
      - game-client

  game-client:
    build: ./packages/game-client
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages/game-client:/usr/src/client:rw
      - ./packages/shared-lib:/usr/src/shared-lib

  game-server:
    build: ./packages/game-server
    networks:
      - backend
    environment:
      - DB_DATABASE
      - DB_USER
      - DB_PASS
      - DB_HOST
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - game-db
    volumes:
      - ./packages/game-server:/usr/src/server:rw
      - ./packages/shared-lib:/usr/src/shared-lib
  
  game-db:
    image: mariadb:5.5.64
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=incorporated_dev
      - MYSQL_DATABASE=incorporated_dev
      - MYSQL_USER=incorporated_dev
      - MYSQL_PASSWORD=incorporated_dev
    ports:
      - 3307:3306 # remove in prod
    volumes:
      - ./.mariadb-docker:/var/lib/mysql

  account-nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "3000:80"
    networks:
      - backend
      - default
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf/logs:/var/log/nginx:rw
      - ./nginx-conf/vhost.d:/etc/nginx/vhost.d
      - ./nginx-conf/conf.d/account-dev/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:rw
      - ./nginx-conf/certs:/etc/nginx/certs:rw
    depends_on:
      - account-server
      - account-client

  account-client:
    build: ./packages/account-client
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages/account-client:/usr/src/client:rw

  account-server:
    build: ./packages/account-server
    networks:
      - backend
    depends_on:
      - account-db
    volumes:
      - ./packages/account-server:/usr/src/server:rw
  
  account-db:
    image: mariadb:5.5.64
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=incorporated_dev
      - MYSQL_DATABASE=incorporated_dev
      - MYSQL_USER=incorporated_dev
      - MYSQL_PASSWORD=incorporated_dev
    ports:
      - 3308:3306 # remove in prod
    volumes:
      - ./.account-mariadb-docker:/var/lib/mysql

networks:
  default:
  backend:
