version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - default
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf/logs:/var/log/nginx:rw
      - ./nginx-conf/vhost.d:/etc/nginx/vhost.d
      - ./nginx-conf/conf.d/dev:/etc/nginx/conf.d
      - ./nginx-conf/certs:/etc/nginx/certs:rw

  client:
    build: ./client
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    volumes:
      - ./client:/usr/src/client:rw
      - ./shared-lib:/usr/src/shared-lib

  server:
    build: ./server
    networks:
      - backend
    environment:
      - DB_DATABASE
      - DB_USER
      - DB_PASS
      - DB_HOST
      - NODE_ENV=dev
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/server:rw
      - ./shared-lib:/usr/src/shared-lib
  
  db:
    image: mariadb:5.5.64
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=incorporated_dev
      - MYSQL_DATABASE=incorporated_dev
      - MYSQL_USER=incorporated_dev
      - MYSQL_PASSWORD=incorporated_dev
    ports:
      - 3307:3306 # remove in prod
    volumes:
      - ./.mariadb-docker:/var/lib/mysql

networks:
  default:
  backend:
